version: "3.8"
services:
  vue-rtc:
    build:
      context: ./vue-rtc
      dockerfile: ./Dockerfile
    networks:
      - rtc
    ports:
      - 8080:8080
    container_name: vue-rtc
    volumes:
      - ../src/vue-rtc:/projectRTC-vue-rtc
  nest-server:
    build:
      context: ./nest-server-rtc
      dockerfile: ./Dockerfile
    networks:
      - rtc
    ports:
      - 8001:8001
    container_name: nest-server-rtc
    volumes:
      - ../src/nest-server-rtc:/projectRTC-nest-server
  proxy:
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    depends_on:
      - vue-rtc
      - nest-server
    ports:
      - 80:80
    networks:
      - rtc
    container_name: proxy
networks:
  rtc:
    driver: bridge
