version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "projectRTC"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[".env".deploy.parameters]
stack_name = "projectRTC"
resolve_s3 = true
s3_prefix = "projectRTC"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
