name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      - name: Archive files
        run: zip -r lambda.zip ./*   # Đây là câu lệnh để nén các tệp vào lambda.zip, giả sử tệp được xây dựng được đặt trong thư mục "dist"

      - name: Preview
        run: ls

      - name: Unzip files
        run: |
          unzip lambda.zip -d extracted   # Đây là câu lệnh để giải nén tệp zip vào thư mục "extracted"

      - name: List extracted files
        run: ls extracted
      # - name: Deploy to Lambda
      #   uses: appleboy/lambda-action@v2
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: "us-east-1"
      #     function_name: "my-lambda-function"
      #     zip_file: lambda.zip
