name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a command
        run: 'echo "Hello, world!"'
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 94.237.79.161 >> ~/.ssh/known_hosts

      - name: Remote SSH command (debug)
        run: |
          ssh -v user@94.237.79.161

      - name: Remote SSH command
        run: |
          ssh user@94.237.79.161

      - name: Test command in server
        run: |
          cd ~/workspace && ls -la
