name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a command
        run: 'echo "Hello, world!"'
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to remote server
        id: ssh
        uses: appleboy/ssh-action@master
        with:
          host: 94.237.79.161
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
           cd workspace && ls -la

      - name: cleanup
        run: rm -rf ~/.ssh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: SSH to remote server
          uses: appleboy/ssh-action@master
          with: ${{ steps.ssh.outputs }}
        - name: Run deployment script
          run: |
            cd workspace && ls -la
