name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a command
        run: 'echo "Hello, world!"'
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: source code
        run: ls

      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 94.237.79.161
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./*
          target: /workspace/testCICD

      - name: cleanup
        run: rm -rf ~/.ssh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: SSH to remote server
          uses: appleboy/ssh-action@master
          with:
            host: 94.237.79.161
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              echo "${{ env.ENV_FE }}" > ./vue-rtc/.env
              echo "${{ env.ENV_BE }}" > ./nest-server-rtc/.env
              echo "${{ env.ENV_PROXY }}" > ./proxy/.env
              cd workspace && ls
