name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-fe:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/develop_fe'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '18'

      - name: Install environments
        run: cd vue-rtc && echo ${{ vars.ENV_FE }} >> .env

      - name: Install dependencies
        run: cd vue-rtc && npm install

      - name: Build
        run: cd vue-rtc && npm run build

      - name: Archive files
        run: cd vue-rtc && zip -r fe.zip ./dist/*

      - name: List file
        run: cd vue-rtc && ls

      - name: unzip file
        run: cd vue-rtc && mkdir unzip unzip fe.zip -d ./unzip

      - name: preview unzip
        run: cd vue-rtc && cd unzip && ls -la

    # - name: Deploy to Lambda
      #   uses: appleboy/lambda-action@v2
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: "us-east-1"
      #     function_name: "my-lambda-function"
      #     zip_file: lambda.zip

  build-and-deploy-be:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/develop_be'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install environments
        run: cd vue-rtc && echo ${{ vars.ENV_FE }} >> .env

      - name: Install dependencies
        run: cd nest-server-rtc && npm install

      - name: Build
        run: cd nest-server-rtc && npm run build

      - name: Archive files
        run: cd nest-server-rtc && zip -r be.zip ./dist/*

      - name: List file
        run: cd nest-server-rtc && ls

      - name: unzip file
        run: cd vue-rtc && mkdir unzip unzip be.zip -d ./unzip

      - name: preview unzip
        run: cd vue-rtc && cd unzip && ls -la
    # - name: Deploy to Lambda
      #   uses: appleboy/lambda-action@v2
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: "us-east-1"
      #     function_name: "my-lambda-function"
      #     zip_file: lambda.zip
