name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a command
        run: 'echo "Hello, world!"'
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqSGmRDsKvE1TFs/p9klRNxrGbKTUDHj/RhZHjJgC4NV9kqu9xkDRHdQQPw/y6DOfZx5GHMxso9OI76mWaVbTKWGGY1rPKIQA9a9GAxSIKsqsJgnCmGUYFvcgK2dmRBeJ27LiXNZ2uJlFhbQ8dXCJ2vPoO7QlIWY7WiIJov19NRXFXd8OR16EK/YijetRQr/gHp4XXO2+sCVU6KNH25w6mKkMV2UmzXq4Qle/fz6Qw0XMUInHbL4y1d9nrpjJtErPNhOSgW0pfJMionkcnO5k1C9Ca5qQLE8jIviZ092IOaIWh6u2uyZXEt/g/2dA3K50KLgu/wuw4K5zXIdD7Pttd root@upcloud-azoompham.the.tho-dev" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 94.237.79.161 >> ~/.ssh/known_hosts

      - name: Remote SSH command
        run: |
          ssh root@94.237.79.161 "ls"

      - name: Test command in server
        run: |
          cd ~/workspace && ls -la
